apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.4
        ports:
        - containerPort: 80
        - hostIP: 0.0.0.0
        - protocol: TCP
      securityContext:  
        capabilities:
          add: ["NET_ADMIN", "SYS_TIME"]
        seLinuxOptions:
          level: "s0:c123,c456" 
        # readOnlyRootFilesystem: true   
        